name: Publish to TestPyPI

# Запускать при пушах в ветку develop
# on:
#   push:
#     branches: [develop]
#     paths-ignore:
#       - '**.md'     # Изменения ТОЛЬКО в .md файлах НЕ запустят workflow
#       - 'docs/**'   # Изменения ТОЛЬКО в docs/ НЕ запустят workflow


on:
  # Ручной запуск через интерфейс GitHub
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Тип обновления версии (patch/minor/major)'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      run_tests:
        description: 'Запускать тесты перед публикацией'
        required: false
        default: true
        type: boolean


jobs:
  build-and-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write  # Обязательно для Trusted Publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          # Добавляем Poetry в PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry # В Githib actions по умолчанию создается виртуальное окружение
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --without dev --no-interaction

      # - name: Run tests # TODO
        # run: poetry run pytest tests/

      - name: Build package
        run: poetry build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          # Пакет будет опубликован с использованием Trusted Publishing
